### ISSUE TITLE
No bots on Escape from Braxis

### ISSUE THREAD

**Issue by clumba** [jamiephan/HeroesOfTheStorm_TryMode2.0Installer#11]
Hi there.

I tried to run map (all versions) and always started the game alone. The bots did not appear. Is there any way to fix this?

**Comment by jamiephan** [comment]
Hi, did you install the AI variant of Escape from Braxis?

![image](https://user-images.githubusercontent.com/9488815/193063184-9e4cf709-c86c-4529-8966-0416343dac6e.png)

From my testing, it does spawn AIs

**Comment by clumba** [comment]
I tried all 4 versions via "Try Mode", no bots. Actually, I saw bots through TAB - that they exist, but none chose a hero.
The bots only started working when I replaced the file on the advice of a person from reddit: https://www.reddit.com/r/heroesofthestorm/comments/xnrq96/comment/ipyvmod/?utm_source=share&utm_medium=web2x&context=3

**Comment by jamiephan** [comment]
Just analyzed the working map file and I have an understanding on how it works.

I'll try to fix on the upstream repo: https://github.com/jamiephan/HeroesOfTheStorm_AIMaps and regenerate the maps in the installer.

Thanks for the report!

**Comment by jamiephan** [comment]
The AI issue for PVE maps have been fixed. Please restart the installer app for the update. Thanks.
