### ISSUE TITLE
Taskbar Name

### ISSUE THREAD

**Issue by Elitesparkle** [jamiephan/HeroesOfTheStorm_TryMode2.0Installer#7]
I suggest to replace "Heroes of the Storm - Try Mode 2.0 Installer" with "Try Mode 2.0 Installer" so that it doesn't get confused with the game in the taskbar when they are both open at the same time.

**Comment by jamiephan** [comment]
Yeah sure. 

I'm also considering to change the icon too, probably just change the colour to better differentiate from the game icon.

**Comment by jamiephan** [comment]
Fixed in #8.

Also updated app icon to a green shade, can be downloaded on version [v1.3.0](https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0Installer/releases/tag/v1.3.0).
